import {
  PenTool,
  Code2,
  Zap,
  Shield,
  Image,
  type LucideIcon,
  FileText,
  SpellCheck,
  BookOpen,
  GitBranch,
  FileSignature,
  FileCheck,
  RefreshCw,
  Search,
  Volume2,
  ImagePlus,
  ScanText,
  Eraser,
  FileDown,
  FileUp,
  ImageDown,
  AlertTriangle,
  Star,
  MessageSquare,
  Flame,
  Bot,
  Braces,
  Eye,
  Wifi,
  Hash,
  QrCode,
  Lock,
  Calculator,
  Ruler,
  Percent,
} from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: string;
  apiType: "gemini" | "local" | "client";
  available: boolean;
}

export interface ToolCategory {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  color: string;
  gradient: string;
  tools: Tool[];
}

export const toolCategories: ToolCategory[] = [
  {
    id: "writing",
    name: "AI Writing Tools",
    description: "Generate, fix, and enhance text with AI-powered writing assistance",
    icon: PenTool,
    color: "#6366f1",
    gradient: "from-indigo-500 to-purple-500",
    tools: [
      {
        id: "grammar",
        name: "Grammar Fix",
        description: "Fix grammar, spelling, and punctuation errors instantly",
        icon: SpellCheck,
        href: "/dashboard/writing/grammar",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "blog",
        name: "Blog Generator",
        description: "Generate professional blog posts from a topic or outline",
        icon: BookOpen,
        href: "/dashboard/writing/blog",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "readme",
        name: "README Generator",
        description: "Create professional GitHub README files automatically",
        icon: GitBranch,
        href: "/dashboard/writing/readme",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "resume-summary",
        name: "Resume Summary",
        description: "Generate compelling resume summaries and bullet points",
        icon: FileSignature,
        href: "/dashboard/writing/resume-summary",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "cover-letter",
        name: "Cover Letter",
        description: "Craft tailored cover letters for any job application",
        icon: FileCheck,
        href: "/dashboard/writing/cover-letter",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "paraphrase",
        name: "Paraphrasing Tool",
        description: "Rewrite text in different styles while preserving meaning",
        icon: RefreshCw,
        href: "/dashboard/writing/paraphrase",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "paragraph-correction",
        name: "Paragraph Correction",
        description: "Restructure and improve paragraph flow and clarity",
        icon: FileText,
        href: "/dashboard/writing/paragraph-correction",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
      {
        id: "plagiarism",
        name: "Plagiarism Checker",
        description: "Detect potential plagiarism in your content",
        icon: Search,
        href: "/dashboard/writing/plagiarism",
        category: "writing",
        apiType: "gemini",
        available: true,
      },
    ],
  },
  {
    id: "media",
    name: "AI Media Tools",
    description: "Transform and convert media files with intelligent processing",
    icon: Image,
    color: "#f472b6",
    gradient: "from-pink-500 to-rose-500",
    tools: [
      {
        id: "tts",
        name: "Text to Speech",
        description: "Convert text to natural-sounding speech audio",
        icon: Volume2,
        href: "/dashboard/media/tts",
        category: "media",
        apiType: "client",
        available: true,
      },
      {
        id: "tti",
        name: "Text to Image",
        description: "Generate images from text descriptions using AI",
        icon: ImagePlus,
        href: "/dashboard/media/tti",
        category: "media",
        apiType: "gemini",
        available: false,
      },
      {
        id: "ocr",
        name: "Image to Text (OCR)",
        description: "Extract text from images with optical character recognition",
        icon: ScanText,
        href: "/dashboard/media/ocr",
        category: "media",
        apiType: "client",
        available: false,
      },
      {
        id: "bg-remover",
        name: "Background Remover",
        description: "Remove backgrounds from images automatically",
        icon: Eraser,
        href: "/dashboard/media/bg-remover",
        category: "media",
        apiType: "client",
        available: false,
      },
      {
        id: "pdf-to-word",
        name: "PDF to Word",
        description: "Convert PDF documents to editable Word format",
        icon: FileDown,
        href: "/dashboard/media/pdf-to-word",
        category: "media",
        apiType: "local",
        available: false,
      },
      {
        id: "word-to-pdf",
        name: "Word to PDF",
        description: "Convert Word documents to PDF format",
        icon: FileUp,
        href: "/dashboard/media/word-to-pdf",
        category: "media",
        apiType: "local",
        available: false,
      },
      {
        id: "image-converter",
        name: "Image Converter",
        description: "Convert images between formats (PNG, JPG, WebP)",
        icon: ImageDown,
        href: "/dashboard/media/image-converter",
        category: "media",
        apiType: "client",
        available: false,
      },
    ],
  },
  {
    id: "detection",
    name: "AI Detection & Analysis",
    description: "Analyze content for authenticity, toxicity, and sentiment",
    icon: Shield,
    color: "#22c55e",
    gradient: "from-emerald-500 to-green-500",
    tools: [
      {
        id: "fake-news",
        name: "Fake News Detector",
        description: "Analyze news articles for potential misinformation",
        icon: AlertTriangle,
        href: "/dashboard/detection/fake-news",
        category: "detection",
        apiType: "gemini",
        available: true,
      },
      {
        id: "ats-score",
        name: "Resume ATS Scoring",
        description: "Score your resume against job descriptions for ATS compatibility",
        icon: Star,
        href: "/dashboard/detection/ats-score",
        category: "detection",
        apiType: "gemini",
        available: true,
      },
      {
        id: "sentiment",
        name: "Sentiment Analysis",
        description: "Analyze the emotional tone and sentiment of text",
        icon: MessageSquare,
        href: "/dashboard/detection/sentiment",
        category: "detection",
        apiType: "gemini",
        available: true,
      },
      {
        id: "toxic-comment",
        name: "Toxic Comment Detector",
        description: "Identify toxic, offensive, or harmful content",
        icon: Flame,
        href: "/dashboard/detection/toxic-comment",
        category: "detection",
        apiType: "gemini",
        available: true,
      },
      {
        id: "ai-detector",
        name: "AI Content Detector",
        description: "Detect whether content was written by AI or human",
        icon: Bot,
        href: "/dashboard/detection/ai-detector",
        category: "detection",
        apiType: "gemini",
        available: true,
      },
    ],
  },
  {
    id: "developer",
    name: "Developer Tools",
    description: "Powerful tools for coding, debugging, and documentation",
    icon: Code2,
    color: "#06b6d4",
    gradient: "from-cyan-500 to-blue-500",
    tools: [
      {
        id: "code-explain",
        name: "Code Explainer",
        description: "Get clear explanations of any code snippet",
        icon: Eye,
        href: "/dashboard/developer/code-explain",
        category: "developer",
        apiType: "gemini",
        available: true,
      },
      {
        id: "code-convert",
        name: "Code Converter",
        description: "Convert code between programming languages",
        icon: RefreshCw,
        href: "/dashboard/developer/code-convert",
        category: "developer",
        apiType: "gemini",
        available: true,
      },
      {
        id: "api-tester",
        name: "API Tester",
        description: "Test REST APIs with a clean, intuitive interface",
        icon: Wifi,
        href: "/dashboard/developer/api-tester",
        category: "developer",
        apiType: "client",
        available: true,
      },
      {
        id: "json-formatter",
        name: "JSON Formatter",
        description: "Format, validate, and beautify JSON data",
        icon: Braces,
        href: "/dashboard/developer/json-formatter",
        category: "developer",
        apiType: "client",
        available: true,
      },
      {
        id: "markdown-preview",
        name: "Markdown Preview",
        description: "Write and preview markdown in real-time",
        icon: Hash,
        href: "/dashboard/developer/markdown-preview",
        category: "developer",
        apiType: "client",
        available: true,
      },
    ],
  },
  {
    id: "productivity",
    name: "Productivity Tools",
    description: "Essential utilities for everyday tasks and calculations",
    icon: Zap,
    color: "#f59e0b",
    gradient: "from-amber-500 to-orange-500",
    tools: [
      {
        id: "qr-generator",
        name: "QR Code Generator",
        description: "Generate customizable QR codes from any text or URL",
        icon: QrCode,
        href: "/dashboard/productivity/qr-generator",
        category: "productivity",
        apiType: "local",
        available: true,
      },
      {
        id: "password-generator",
        name: "Password Generator",
        description: "Create strong, secure passwords with custom rules",
        icon: Lock,
        href: "/dashboard/productivity/password-generator",
        category: "productivity",
        apiType: "client",
        available: true,
      },
      {
        id: "emi-calculator",
        name: "EMI Calculator",
        description: "Calculate monthly installments for loans",
        icon: Calculator,
        href: "/dashboard/productivity/emi-calculator",
        category: "productivity",
        apiType: "client",
        available: true,
      },
      {
        id: "unit-converter",
        name: "Unit Converter",
        description: "Convert between different measurement units",
        icon: Ruler,
        href: "/dashboard/productivity/unit-converter",
        category: "productivity",
        apiType: "client",
        available: true,
      },
      {
        id: "percentage-calculator",
        name: "Percentage Calculator",
        description: "Calculate percentages, discounts, and ratios",
        icon: Percent,
        href: "/dashboard/productivity/percentage-calculator",
        category: "productivity",
        apiType: "client",
        available: true,
      },
    ],
  },
];

export function getAllTools(): Tool[] {
  return toolCategories.flatMap((cat) => cat.tools);
}

export function getToolById(id: string): Tool | undefined {
  return getAllTools().find((t) => t.id === id);
}

export function getCategoryById(id: string): ToolCategory | undefined {
  return toolCategories.find((cat) => cat.id === id);
}

export function getAvailableTools(): Tool[] {
  return getAllTools().filter((t) => t.available);
}
